name: Run IMDB Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies directly
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow mlflow numpy scikit-learn

      # 4. Debug: Show repo structure
      - name: Show repo files
        run: ls -R

      # 5. Run training script
      - name: Run training script
        run: python "Ml and Dl Projects with Mlops/dl_projects_lstm_with_mlflow/train_imdb.py"
