name: Run IMDB LSTM Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow scikit-learn mlflow numpy

      # 4. Set Databricks credentials manually
      - name: Set Databricks environment variables
        run: |
          echo "DATABRICKS_HOST=https://dbc-24fe64fc-5231.cloud.databricks.com" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=dapi525ed5b453b93e8a21477ba74d8314f6" >> $GITHUB_ENV

      # 5. Debug: Show repo structure (optional)
      - name: Show repo files
        run: ls -R

      # 6. Run training script
      - name: Run training script
        run: python "Ml and Dl Projects with Mlops/dl_projects_lstm_with_mlflow/train_imdb.py"
