name: IMDB LSTM Databricks CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow scikit-learn mlflow numpy

      # Step 4: Run the IMDB LSTM script
      - name: Run IMDB LSTM script
        run: |
          python "Ml and Dl Projects with Mlops/dl_projects_lstm_with_mlflow/train_imdb.py"

      # Optional: Set Databricks environment variables (if needed)
      # - name: Set Databricks environment variables
      #   env:
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
