stages:
  prepare:
    cmd: python data2/src3/prepare.py
    deps:
      - data2/src3/prepare.py
    outs:
      - data/processed/imdb.npz

  train:
    cmd: python data2/src3/train.py
    deps:
      - data2/src3/train.py
      - data/processed/imdb.npz
    outs:
      - model/imdb_lstm.h5

  evaluate:
    cmd: python data2/src3/evaluate.py
    deps:
      - data2/src3/evaluate.py
      - model/imdb_lstm.h5
      - data/processed/imdb.npz
    metrics:
      - metrics.json
