stages:
  load_data:
    cmd: python src/load_data.py
    deps:
      - src/load_data.py
      - data/raw/data.csv
    outs:
      - data/loaded/data.csv

  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/loaded/data.csv
    outs:
      - data/processed
    params:
      - data.target_column
      - preprocessing.test_size
      - preprocessing.random_state

  train_model:
    cmd: python src/model.py
    deps:
      - src/model.py
      - data/processed
    outs:
      - models/model.joblib
    params:
      - training.model_path

  evaluate:
    cmd: python src/evaluation.py
    deps:
      - src/evaluation.py
      - models/model.joblib
      - data/processed
    metrics:
      - evaluation/metrics.json
    params:
      - evaluation.metrics_path

