apiVersion: v1
kind: Namespace
metadata:
  name: heart-ml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-ml
  namespace: heart-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-ml
  template:
    metadata:
      labels:
        app: heart-ml
    spec:
      containers:
      - name: heart-ml
        image: heart-ml-app:latest   # Local Docker image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: heart-ml-service
  namespace: heart-ml
spec:
  selector:
    app: heart-ml
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: heart-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
       - name: heart-ml
      image: heart-ml-app:latest
      ports:
       - containerPort: 8000
  
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: heart-ml
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: heart-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
        containers:
        - name: heart-ml
        image: heart-ml-app:latest   # Local Docker image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: heart-ml
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
