prepare:
  max_features: 10000
  maxlen: 200

train:
  batch_size: 64
  epochs: 1
  lstm_units: 64
  embedding_dim: 128
  dropout: 0.2
  recurrent_dropout: 0.2
  optimizer: "adam"
  loss: "binary_crossentropy"

evaluate:
  threshold: 0.5
