data:
  raw_path: data/raw/data.csv       # Input raw data
  processed_path: data/processed    # Folder to store processed files
  target_column: "Price ($)"        # Target variable name

preprocessing:
  test_size: 0.3                    # Train/test split ratio
  random_state: 42                  # Reproducibility seed
  drop_missing: true                # Whether to drop rows with missing values
  scaling: standard                 # Options: standard, minmax, none

training:
  model_type: linear_regression     # Currently only LinearRegression
  model_path: models/model.joblib   # Where to save trained model

evaluation:
  metrics_path: evaluation/metrics.json
# Where to save evaluation metrics
