name: Train Student Performance Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4️⃣ Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r ML-Projects/requirements.txt

      # 5️⃣ Run the student performance training script
      - name: Run training script
        run: python ML-Projects/scripts/students_code.py
