name: Train Student Performance Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------
    # 1. Checkout repository
    # -------------------------------
    - name: Checkout repository
      uses: actions/checkout@v3

    # -------------------------------
    # 2. Set up Python 3.10
    # -------------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # -------------------------------
    # 3. Upgrade pip
    # -------------------------------
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # -------------------------------
    # 4. Install dependencies
    # -------------------------------
    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn numpy

    # -------------------------------
    # 5. Run the training script
    # -------------------------------
    - name: Run training script
      run: python ML-Projects/train_student_performance_mlflow.py

    # -------------------------------
    # 6. Optional: Upload artifacts
    # -------------------------------
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-preprocessor
        path: ML-Projects/scaler_pca.npz
