name: Train Student Performance Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install numpy pandas scikit-learn joblib

      # 4️⃣ Run the training script
      - name: Run training
        run: |
          python ML-Projects/train_student_performance.py

      # 5️⃣ (Optional) Upload model and preprocessor as artifacts
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: student-performance-model
          path: |
            ML-Projects/linear_regression_model.pkl
            ML-Projects/scaler_pca.npz
