name: Train Student Performance MLflow

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      # Databricks credentials stored as GitHub secrets
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run ML training script
      - name: Run training script
        run: python dl_projects_lstm_with_mlflow/student_code.py

      # Optional: list MLflow artifacts (if needed)
      # - name: List MLflow artifacts
      #   run: mlflow artifacts list --experiment-name "/Shared/Student-Performance"
