name: Train Student Performance Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-student-performance:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ML-Projects/requirements.txt

      # 4️⃣ Run the student performance training script
      - name: Run training script
        run: python ML-Projects/scripts/students_code.py
