name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies (adjust if you have requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Optional: install other packages here
          # pip install -r requirements.txt

      # Run your script
      - name: Run Python script
        run: python ML-Projects/scripts/students_code.py
