name: Run Student Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-student-script:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies from requirements.text
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.text

      # 4️⃣ Run the student code script
      - name: Run students_code.py
        run: python ML-Projects/scripts/students_code.py
