name: Run Student ML Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-student-code:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r ML-Projects/requirements.txt

      # 5️⃣ Run the Python script
      - name: Run student code
        run: python ML-Projects/scripts/students_code.py
