name: Train Student Performance MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-mlflow:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mlflow scikit-learn pandas numpy

      # 4️⃣ Run MLflow training script
      - name: Run student MLflow training
        run: |
          python ML-Projects/train_student_performance_mlflow.py

      # 5️⃣ Upload artifacts (optional: preprocessor or other files)
      - name: Upload ML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor-and-model
          path: |
            scaler_pca.npz
            ML-Projects/scripts/students_code.py
